console.log("**step1**");
var myFullName;
console.log(myFullName);
myFullName="Yogita Dudhani";
console.log(myFullName);
myFullName="Yogita Chandrashekhar Dudhani";
console.log(myFullName);
console.log("**step2**");
var myLove="I Love only JS";
console.log(myLove);
console.log("**step3**");
var firstName="yogita";
var lastName="dudhani";
var age="26";
var address="Sangola";
var pincode="413307";
var gender="female";
var isMarried="yes";
console.log(firstName,lastName,age,address,pincode,gender,isMarried);