console.log("**first assignment of data type**");
var myName="Yogita";
var age=26;
var isMarried=true;
console.log("Name=",myName,typeof(myName));
console.log("age=",age,typeof(age));
console.log("IsMarried=",isMarried,typeof(isMarried));
var x;
console.log(typeof(x));
x=null;
console.log(typeof(x));
console.log("**second assignment of data type**");
var bankName;
console.log(typeof(bankName));
bankName="SBI Bank";
console.log(typeof(bankName));
var marks='90%';
console.log(typeof(marks));
var isWorking;
console.log(isWorking,"before initialization type is",typeof(isWorking));
isWorking=true;
console.log(isWorking,"after initialization type is",typeof(isWorking));
var totalCount="hundred and seven";
console.log(totalCount,typeof(totalCount));
totalCount=107;
console.log(totalCount,typeof(totalCount));